name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCXr2bwg7KSJ177NksgqBUGw
          max_videos: 4
          commit_message: "docs: Update README profile with latest youtube videos"
          author_name: youtube-video-bot
          author_email: youtube-video-bot@alansolidum.com
          card_width: 315
          background_color: "#515254"
          